import type { CityPage, HoursRow, HubData, Listing } from "./types";

export const SITE_URL = "https://dfwgaragedoorinstallers.com";

export const SITE = {
  name: "DFW Garage Door Installers",
  tagline:
    "A local directory for new garage door installation across the Dallas–Fort Worth–Arlington metro — new construction and replacement, not repair-first.",
  keyword: "garage door install Dallas Fort Worth",
};

export const SOURCES = [
  {
    label: "U.S. Census Bureau, Building Permits Survey, 2025 annual (released 14 May 2026)",
    href: "https://www.census.gov/permits",
  },
  {
    label: "Census BPS 2025 annual highlights — metro rankings by total units",
    href: "https://www.census.gov/construction/bps/pdf/annual_highlights.pdf",
  },
  {
    label: "Census BPS CBSA annual 2025 (CBSA 19100)",
    href: "https://www2.census.gov/econ/bps/CBSA%20(beginning%20Jan%202024)/cbsa2025a.txt",
  },
  {
    label: "Census BPS county annual 2025",
    href: "https://www2.census.gov/econ/bps/County/co2025a.txt",
  },
  {
    label: "Census BPS South place annual 2025",
    href: "https://www2.census.gov/econ/bps/Place/South%20Region/so2025a.txt",
  },
  {
    label: "Census Vintage 2025 population estimates (metro, county, and place)",
    href: "https://www.census.gov/programs-surveys/popest.html",
  },
];

function hrs(weekday: string, sat: string): HoursRow[] {
  return [
    { days: "Mon–Fri", time: weekday },
    { days: "Saturday", time: sat },
    { days: "Sunday", time: "Closed" },
  ];
}

const SAMPLE_DISCLAIMER =
  "Sample listing for this mockup. Not a real company. Hours, amenities, and addresses are fictional.";

export const HUB: HubData = {
  path: "/tx/dallas-fort-worth/garage-door-install/",
  h1: "Garage door install in Dallas–Fort Worth–Arlington",
  title:
    "Garage Door Install Dallas Fort Worth | DFW Garage Door Install",
  description:
    "Directory of garage door install in Dallas Fort Worth: new construction and replacement across the Dallas–Fort Worth–Arlington MSA, not Dallas city limits. Census BPS 2025 and Vintage 2025 PEP.",
  intro: [
    "This is a directory for garage door install Dallas Fort Worth: new doors on new houses and replacements in the growth suburbs, not a Dallas city-limits repair page. The map is the Dallas–Fort Worth–Arlington MSA (CBSA 19100) — 8,477,157 people on 1 July 2025, 39,790 one-unit permits in 2025. Collin and Denton took 44% of those one-unit homes, which is why the city pages sit on Fort Worth plus the north spine, not inner-ring Dallas.",
  ],
  stats: [
    {
      label: "MSA population",
      value: "8,477,157",
      note: "1 Jul 2025 · Vintage 2025 PEP · CBSA 19100",
    },
    {
      label: "One-unit permits, 2025",
      value: "39,790",
      note: "Census BPS annual, with imputation",
    },
    {
      label: "Total units authorized, 2025",
      value: "66,179",
      note: "#1 metropolitan CBSA for total units",
    },
    {
      label: "Collin + Denton share",
      value: "44%",
      note: "11,136 + 6,357 of MSA one-unit",
    },
  ],
  sections: [
    {
      id: "what-this-directory-covers",
      title: "What this directory covers",
      paragraphs: [
        "City pages list shops that name that city in their service area. This hub lists DFW-wide shops. Install means new construction and planned replacement. Repair — springs, cables, openers on an existing door — is out of scope. Dallas city is a principal city inside the metro, not a ninth mill page.",
      ],
    },
  ],
  toc: [
    { id: "intro", label: "Metro snapshot" },
    { id: "listings", label: "Metro installers" },
    { id: "what-this-directory-covers", label: "What this covers" },
    { id: "cities", label: "City pages" },
    { id: "map", label: "Area map" },
    { id: "sources", label: "Sources" }
  ],
  listings: [
    {
      id: "hub-1",
      name: "Metroplex New Door Desk",
      slug: "metroplex-new-door-desk",
      blurb:
        "Mock multi-crew shop aimed at builder walkthroughs in Collin, Denton, and Tarrant — not a spring-repair van.",
      address: "4200 Sample Yard Rd, Grapevine, TX 76051",
      phone: "(817) 555-0140",
      hours: hrs("7:00 a.m. – 6:00 p.m.", "8:00 a.m. – 2:00 p.m."),
      amenities: [
        "New-construction punch lists",
        "Two- and three-car insulated steel",
        "HOA elevation packets",
        "Builder Saturday slots",
      ],
      photoStyle: "flush",
      photoTint: "#6b5344",
      lat: 32.9343,
      lng: -97.0789,
      serviceNotes: SAMPLE_DISCLAIMER,
    },
    {
      id: "hub-2",
      name: "North Spine Carriage Works",
      slug: "north-spine-carriage-works",
      blurb:
        "Sample studio for carriage-style and stained-wood lookalikes on new Collin County spec houses.",
      address: "118 Mock Seed Row, Plano, TX 75024",
      phone: "(214) 555-0188",
      hours: hrs("8:00 a.m. – 5:00 p.m.", "9:00 a.m. – 1:00 p.m."),
      amenities: [
        "Carriage and overlay doors",
        "Paint-matched to brick/stone",
        "Quiet belt-drive openers",
        "Design-center samples",
      ],
      photoStyle: "carriage",
      photoTint: "#4a3728",
      lat: 33.075,
      lng: -96.821,
      serviceNotes: SAMPLE_DISCLAIMER,
    },
    {
      id: "hub-3",
      name: "CBSA 19100 Overhead Co.",
      slug: "cbsa-19100-overhead-co",
      blurb:
        "Invented regional installer used on this hub to show a metro-wide card, not a city-only shop.",
      address: "900 Fiction Belt Line, Irving, TX 75062",
      phone: "(972) 555-0162",
      hours: hrs("7:30 a.m. – 5:30 p.m.", "8:00 a.m. – 12:00 p.m."),
      amenities: [
        "MSA-wide new installs",
        "Wind-load hardware packages",
        "Wi-Fi opener setup",
        "Inspection-day callbacks",
      ],
      photoStyle: "contemporary",
      photoTint: "#3d4a52",
      lat: 32.814,
      lng: -96.948,
      serviceNotes: SAMPLE_DISCLAIMER,
    },
    {
      id: "hub-4",
      name: "Replacement Bay North Texas",
      slug: "replacement-bay-north-texas",
      blurb:
        "Mock listing for first-generation suburb replacements — same growth cities, older doors, not emergency repair.",
      address: "55 Example Orchard, Lewisville, TX 75067",
      phone: "(469) 555-0194",
      hours: hrs("7:00 a.m. – 6:00 p.m.", "7:00 a.m. – 3:00 p.m."),
      amenities: [
        "Same-size replacement",
        "Insulation upgrades",
        "Opener included packages",
        "Color-match to faded brick",
      ],
      photoStyle: "wood",
      photoTint: "#7a4e2d",
      lat: 33.046,
      lng: -97.0,
      serviceNotes: SAMPLE_DISCLAIMER,
    },
  ],
  lat: 32.7767,
  lng: -96.797,
  mapLabel: "Dallas–Fort Worth–Arlington MSA",
};

export const CITIES = [
  {
    slug: "fort-worth",
    name: "Fort Worth",
    shortName: "Fort Worth",
    county: "Tarrant County (city also reaches Denton, Parker, and Wise)",
    path: "/tx/fort-worth/garage-door-install/",
    h1: "Garage door installation in Fort Worth",
    title: "Garage Door Installation Fort Worth TX | New Garage Door Fort Worth",
    description:
      "Garage door installation in Fort Worth: new construction and replacement. Fort Worth led the DFW MSA in 2025 one-unit permits (5,887). Census BPS 2025 and Vintage 2025 PEP.",
    kicker: "Largest 1-unit permit office in the metro",
    intro: [
      "Fort Worth is the west-side install heavyweight: 1,028,117 people and 5,887 one-unit permits in 2025, the largest place office in the metro. New doors sit on the far-north Alliance edge, west toward Walsh Ranch, and the south fringe — builder punch lists, not downtown infill. This page is new doors and planned replacements, not broken springs.",
    ],
    stats: [
      { label: "Population", value: "1,028,117", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+109,225", note: "+11.9% from 2020 estimates base" },
      { label: "2025 1-unit permits", value: "5,887", note: "BPS place “Fort Worth”; 2024: 6,257" },
    ],
    sections: [
      {
        id: "where-the-new-doors-go",
        title: "Where the new doors actually go",
        paragraphs: [
          "Keep two streams straight when you call: punch-list new construction on the fringe vs. measured replacement in east and near-south openings. Tarrant County permitted 8,658 one-unit homes in 2025; Fort Worth’s office is most of that volume.",
        ],
      },
    ],
    neighborhoods: [
      { name: "Far North / Alliance edge", note: "Builder production; two- and three-car steel doors on new slabs." },
      { name: "Westside / Walsh Ranch–facing growth", note: "Design-forward elevations; carriage and flush mixed." },
      { name: "South Fort Worth fringe", note: "Master-plan one-unit; punch-list scheduling matters more than brand." },
      { name: "Established east and near-south", note: "Replacement in existing openings; not the 5,887-permit story." },
    ],
    toc: [
      { id: "intro", label: "Fort Worth snapshot" },
      { id: "listings", label: "Installers" },
      { id: "where-the-new-doors-go", label: "Where new doors go" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "fw-1",
        name: "Trinity Fork Install Co.",
        slug: "trinity-fork-install-co",
        blurb: "Mock Fort Worth shop for new-construction punch lists on the far-north and west edges.",
        address: "8100 Sample Alliance Trl, Fort Worth, TX 76177",
        phone: "(817) 555-0101",
        hours: hrs("6:30 a.m. – 5:30 p.m.", "7:00 a.m. – 1:00 p.m."),
        amenities: ["Builder punch lists", "Insulated flush steel", "Three-car openings", "Inspection callbacks"],
        photoStyle: "flush",
        photoTint: "#5c4033",
        lat: 32.967,
        lng: -97.31,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fw-2",
        name: "Westside Carriage Doors",
        slug: "westside-carriage-doors",
        blurb: "Sample carriage-style installer aimed at design-center upgrades, not emergency springs.",
        address: "221 Fiction Camp Bowie, Fort Worth, TX 76107",
        phone: "(817) 555-0108",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "10:00 a.m. – 2:00 p.m."),
        amenities: ["Carriage overlays", "Stain-look steel", "HOA photo packets", "Quiet belt drive"],
        photoStyle: "carriage",
        photoTint: "#3f2a1d",
        lat: 32.748,
        lng: -97.388,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fw-3",
        name: "Stockyards Panel & Track",
        slug: "stockyards-panel-track",
        blurb: "Invented north-central Fort Worth crew for replacements near older stock plus new infill.",
        address: "140 Sample Exchange Ave, Fort Worth, TX 76164",
        phone: "(817) 555-0114",
        hours: hrs("7:00 a.m. – 6:00 p.m.", "8:00 a.m. – 2:00 p.m."),
        amenities: ["Same-opening replacement", "Wind-load tracks", "Opener packages", "Color-match consult"],
        photoStyle: "wood",
        photoTint: "#6a3e24",
        lat: 32.789,
        lng: -97.348,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fw-4",
        name: "Clear Fork Overhead",
        slug: "clear-fork-overhead",
        blurb: "Mock west-side company used to show RV-height and three-car new installs.",
        address: "5600 Example Hulen, Fort Worth, TX 76132",
        phone: "(817) 555-0122",
        hours: hrs("7:00 a.m. – 5:00 p.m.", "Closed"),
        amenities: ["RV-height bays", "Two-car doubles", "Smart opener setup", "Saturday builder only by appointment"],
        photoStyle: "contemporary",
        photoTint: "#445055",
        lat: 32.672,
        lng: -97.4,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fw-5",
        name: "Ridglea New Door Works",
        slug: "ridglea-new-door-works",
        blurb: "Sample listing mixing inner-west replacement with south-fringe new construction.",
        address: "77 Mock Ridglea Pkwy, Fort Worth, TX 76116",
        phone: "(817) 555-0129",
        hours: hrs("8:00 a.m. – 5:30 p.m.", "9:00 a.m. – 12:00 p.m."),
        amenities: ["Insulation upgrades", "Short-panel steel", "Pedestrian-door add-ons", "Written measure"],
        photoStyle: "glass",
        photoTint: "#4d5a63",
        lat: 32.722,
        lng: -97.418,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 32.7555,
    lng: -97.3308,
    mapLabel: "Fort Worth, TX",
    related: ["celina", "mckinney", "frisco", "denton"],
  },
  {
    slug: "celina",
    name: "Celina",
    shortName: "Celina",
    county: "Collin County",
    path: "/tx/celina/garage-door-install/",
    h1: "Garage door installation in Celina",
    title: "Garage Door Installation Celina TX | New Garage Door Celina",
    description:
      "Garage door installation in Celina, Texas — the DFW suburb with the highest 2025 one-unit permit count (2,489) and +276.8% population growth since 2020.",
    kicker: "Highest 1-unit suburb in DFW, 2025",
    intro: [
      "Celina is the extreme Collin growth suburb: 64,427 people (+276.8% since 2020) and 2,489 one-unit permits in 2025, the highest suburb print in this directory. Garage door installation here is almost entirely new construction on lots that were farmland a few years ago. Replacement stock is still young.",
    ],
    stats: [
      { label: "Population", value: "64,427", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+276.8%", note: "Steepest large-place trajectory in this set" },
      { label: "2025 1-unit permits", value: "2,489", note: "BPS; 2024: 2,905" },
    ],
    sections: [
      {
        id: "why-celina",
        title: "Why Celina is an install page",
        paragraphs: [
          "A useful Celina card names builder calendars, HOA elevation photos, and insulated steel — not a generic garage-door company. 2,489 is a lower bound; some Celina-area houses are permitted in a county office.",
          "Celina's population base was 17,099 in 2020; the 47,328 added since then is why 2,489 one-unit permits reads as normal here, not an anomaly. Growth was still steep in the newest count, up 24.6% from 2024 to 2025, even as the one-unit print itself eased from 2,905 to 2,489. Celina sits inside Collin County, which alone permitted 11,136 of the metro's 39,790 one-unit homes in 2025. On this page, install means a garage door going onto a new one-unit house; a broken spring, cable, or opener on an existing door is repair, which this directory does not cover.",
        ],
      },
    ],
    neighborhoods: [
      { name: "Master-plan west / Light Farms–scale growth", note: "Highest density of new two- and three-car openings." },
      { name: "Dallas North Tollway north", note: "New sections still releasing; builder doors first." },
      { name: "Toward downtown Celina", note: "Mix of new product and a small older core for later replacement." },
      { name: "ETJ / county-line lots", note: "May be permitted outside the Celina place office; still Celina-search demand." },
    ],
    toc: [
      { id: "intro", label: "Celina snapshot" },
      { id: "listings", label: "Installers" },
      { id: "why-celina", label: "Why this page" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "ce-1",
        name: "Light Farms Door Studio",
        slug: "light-farms-door-studio",
        blurb: "Mock design-forward shop for carriage and overlay doors on new Celina elevations.",
        address: "1000 Sample Light Farms Way, Celina, TX 75009",
        phone: "(972) 555-0201",
        hours: hrs("7:30 a.m. – 5:30 p.m.", "9:00 a.m. – 1:00 p.m."),
        amenities: ["Carriage overlays", "HOA elevation JPEGs", "Color-matched steel", "Design-center samples"],
        photoStyle: "carriage",
        photoTint: "#5a3a28",
        lat: 33.338,
        lng: -96.805,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "ce-2",
        name: "North Collin Carriage",
        slug: "north-collin-carriage",
        blurb: "Sample installer for production-builder punch lists in north Collin.",
        address: "440 Fiction Dallas Pkwy N, Celina, TX 75009",
        phone: "(214) 555-0208",
        hours: hrs("6:30 a.m. – 5:00 p.m.", "7:00 a.m. – 12:00 p.m."),
        amenities: ["Builder Saturday slots", "Insulated flush", "Three-car layouts", "Opener allowance upgrades"],
        photoStyle: "flush",
        photoTint: "#6e6254",
        lat: 33.351,
        lng: -96.79,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "ce-3",
        name: "Future Fields Install",
        slug: "future-fields-install",
        blurb: "Invented crew name for still-releasing sections — new slabs, not repair vans.",
        address: "80 Example Ownby, Celina, TX 75009",
        phone: "(469) 555-0215",
        hours: hrs("7:00 a.m. – 6:00 p.m.", "8:00 a.m. – 2:00 p.m."),
        amenities: ["New-slab scheduling", "Wind-load hardware", "Wi-Fi opener setup", "Two-car doubles"],
        photoStyle: "contemporary",
        photoTint: "#3c4942",
        lat: 33.31,
        lng: -96.77,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "ce-4",
        name: "Celina Ridge Overhead",
        slug: "celina-ridge-overhead",
        blurb: "Mock listing covering Celina plus nearby county-line lots people still search as Celina.",
        address: "12 Sample Business 289, Celina, TX 75009",
        phone: "(972) 555-0220",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "Closed"),
        amenities: ["ETJ / city-line jobs", "Written measure", "Insulation packages", "Inspection-day callback"],
        photoStyle: "wood",
        photoTint: "#7a5130",
        lat: 33.3246,
        lng: -96.754,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.3246,
    lng: -96.7844,
    mapLabel: "Celina, TX",
    related: ["mckinney", "princeton", "anna", "melissa", "frisco"],
  },
  {
    slug: "mckinney",
    name: "McKinney",
    shortName: "McKinney",
    county: "Collin County",
    path: "/tx/mckinney/garage-door-install/",
    h1: "Garage door installation in McKinney",
    title: "Garage Door Installation McKinney TX | New Garage Door McKinney",
    description:
      "Garage door installation in McKinney, Texas. Population 236,001 (+20.8% since 2020); 1,649 one-unit permits in 2025. New construction and replacement directory.",
    kicker: "Collin county seat still permitting four-digit 1-unit",
    intro: [
      "McKinney is the large named Collin city that is not Frisco: 236,001 people (+20.8%) and 1,649 one-unit permits in 2025. North and east (Trinity Falls–scale growth) is new construction. Near the square and in 1990s–2010s subdivisions, it is replacement in an existing opening. Both are install.",
    ],
    stats: [
      { label: "Population", value: "236,001", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+20.8%", note: "+40,670 people" },
      { label: "2025 1-unit permits", value: "1,649", note: "BPS; 2024: 2,388" },
    ],
    sections: [
      {
        id: "two-mckinneys",
        title: "Two McKinneys, one install page",
        paragraphs: [
          "The 1,649 permits did not happen on the historic square. They sit north toward 121 and east toward Princeton. One-unit cooled from 2,388 in 2024; that is still well over a thousand new houses, not a built-out inner-ring print.",
          "McKinney added 40,670 people from a 2020 base of 195,331 (+20.8%), then slowed to +3.7% from 2024 to 2025 as the city matured past its steepest climb. One-unit permits still ran to 1,649 in 2025 (total units 3,040), inside Collin County's 11,136, and McKinney's numeric population gain trails only Fort Worth and Celina among DFW cities. That volume sits on the Collin growth spine — north of the square toward 121, east toward Princeton, with Anna and Melissa further out on US-75. Install here is a door on a new-construction one-unit house, or a planned replacement in an existing opening. Springs, cables, and openers on an existing door are out of scope.",
        ],
      },
    ],
    neighborhoods: [
      { name: "North / Trinity Falls–scale growth", note: "New construction; builder doors and upgrades." },
      { name: "East toward Princeton / 380", note: "Still-releasing one-unit; overlap with Princeton search." },
      { name: "Historic square and near-in", note: "Replacement and small infill, not the permit volume." },
      { name: "Established 1990s–2010s west and south", note: "First replacement wave on existing openings." },
    ],
    toc: [
      { id: "intro", label: "McKinney snapshot" },
      { id: "listings", label: "Installers" },
      { id: "two-mckinneys", label: "Two McKinneys" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "mk-1",
        name: "Heard Homestead Doors",
        slug: "heard-homestead-doors",
        blurb: "Mock north-McKinney shop for new-construction carriage and flush installs.",
        address: "5000 Sample Trinity Falls Pkwy, McKinney, TX 75071",
        phone: "(972) 555-0301",
        hours: hrs("7:00 a.m. – 5:30 p.m.", "8:00 a.m. – 1:00 p.m."),
        amenities: ["New-construction installs", "Carriage and flush", "HOA packets", "Three-car openings"],
        photoStyle: "carriage",
        photoTint: "#4e3423",
        lat: 33.247,
        lng: -96.67,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "mk-2",
        name: "Adriatica Panel Co.",
        slug: "adriatica-panel-co",
        blurb: "Sample listing for design-forward doors near mixed-use and amenity-heavy sections.",
        address: "210 Fiction Adriatica Pkwy, McKinney, TX 75070",
        phone: "(214) 555-0306",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "10:00 a.m. – 2:00 p.m."),
        amenities: ["Full-view glass options", "Paint-match consult", "Quiet belt drive", "Design samples"],
        photoStyle: "glass",
        photoTint: "#4a5560",
        lat: 33.168,
        lng: -96.66,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "mk-3",
        name: "East Fork Install",
        slug: "east-fork-install",
        blurb: "Invented east-side crew covering McKinney lots that shop Princeton in the same search.",
        address: "8800 Example US-380, McKinney, TX 75069",
        phone: "(469) 555-0312",
        hours: hrs("6:30 a.m. – 6:00 p.m.", "7:00 a.m. – 2:00 p.m."),
        amenities: ["380-corridor new installs", "Builder punch lists", "Wind-load tracks", "Opener packages"],
        photoStyle: "flush",
        photoTint: "#5d5346",
        lat: 33.198,
        lng: -96.58,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "mk-4",
        name: "Stonebridge Overhead",
        slug: "stonebridge-overhead",
        blurb: "Mock replacement-leaning installer for established west McKinney openings.",
        address: "33 Sample Lake Forest, McKinney, TX 75070",
        phone: "(972) 555-0318",
        hours: hrs("7:30 a.m. – 5:00 p.m.", "8:00 a.m. – 12:00 p.m."),
        amenities: ["Same-size replacement", "Insulation upgrades", "Color-match to brick", "Written measure"],
        photoStyle: "wood",
        photoTint: "#6b4423",
        lat: 33.175,
        lng: -96.72,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.1972,
    lng: -96.6397,
    mapLabel: "McKinney, TX",
    related: ["celina", "princeton", "frisco", "anna", "melissa"],
  },
  {
    slug: "princeton",
    name: "Princeton",
    shortName: "Princeton",
    county: "Collin County",
    path: "/tx/princeton/garage-door-install/",
    h1: "Garage door installation in Princeton",
    title: "Garage Door Installation Princeton TX | New Garage Door Princeton",
    description:
      "Garage door installation in Princeton, Texas. Population 43,524 (+156.1% since 2020) with 1,598 one-unit permits in 2025. New-construction install directory.",
    kicker: "Still extreme growth, ~1,600 new 1-unit homes",
    intro: [
      "Princeton is the east-Collin surge city: 43,524 people (+156.1%) and 1,598 one-unit permits in 2025. This is a new-construction page — doors on houses that just got sheetrock along US-380 and the Lavon-facing growth, not a repair van on an old farm road.",
    ],
    stats: [
      { label: "Population", value: "43,524", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+156.1%", note: "+26,528 people" },
      { label: "2025 1-unit permits", value: "1,598", note: "BPS; 2024: 1,948" },
    ],
    sections: [
      {
        id: "380-story",
        title: "The 380 story",
        paragraphs: [
          "McKinney is the larger neighbor west; Anna and Melissa sit on the US-75 cluster. One-unit cooled from 1,948 to 1,598 and is still a top suburb print here, ahead of Frisco’s 1,090 one-unit.",
          "Princeton's 2020 base was 16,996; the city added 26,528 people (+156.1%), including +18.1% from 2024 to 2025. A superseded Vintage 2024 press release called Princeton the fastest-growing U.S. city of 20k+ for 2023–24; Vintage 2025 still shows extreme growth and 1,598 one-unit permits in 2025. Princeton sits on the east-Collin / US-380 end of the northern growth spine, east of McKinney and near the US-75 Anna–Melissa cluster — high growth-rate install demand, not Fort Worth's 5,887-permit west-side volume. Replacement stock is still small because most of the housing is new. Install on this page means a door going onto a just-built one-unit frame, not a spring or cable fix on an existing door.",
        ],
      },
    ],
    neighborhoods: [
      { name: "US-380 corridor", note: "Primary new one-unit; two-car production doors." },
      { name: "Toward Lavon Lake", note: "Still-releasing sections; install-new, not repair." },
      { name: "Older town core", note: "Small replacement set; not the 1,598-permit story." },
      { name: "West toward McKinney", note: "Search overlap; check both city pages." },
    ],
    toc: [
      { id: "intro", label: "Princeton snapshot" },
      { id: "listings", label: "Installers" },
      { id: "380-story", label: "The 380 story" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "pr-1",
        name: "Lavon Lake Carriage",
        slug: "lavon-lake-carriage",
        blurb: "Mock east-Collin shop for new two-car doors on still-releasing Princeton streets.",
        address: "1900 Sample Monte Carlo, Princeton, TX 75407",
        phone: "(972) 555-0402",
        hours: hrs("7:00 a.m. – 6:00 p.m.", "8:00 a.m. – 2:00 p.m."),
        amenities: ["New-slab installs", "Insulated steel", "Same-street multi-house days", "Opener packages"],
        photoStyle: "flush",
        photoTint: "#675445",
        lat: 33.17,
        lng: -96.48,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "pr-2",
        name: "Cypress Ridge Door Co.",
        slug: "cypress-ridge-door-co",
        blurb: "Sample carriage-style listing for HOA elevations in larger Princeton sections.",
        address: "400 Fiction Cypress Creek, Princeton, TX 75407",
        phone: "(214) 555-0409",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "9:00 a.m. – 1:00 p.m."),
        amenities: ["Carriage overlays", "HOA JPEGs", "Color-match", "Quiet belt drive"],
        photoStyle: "carriage",
        photoTint: "#4a3020",
        lat: 33.19,
        lng: -96.51,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "pr-3",
        name: "East Collin New Doors",
        slug: "east-collin-new-doors",
        blurb: "Invented regional name for Princeton plus 380 lots people still call Princeton.",
        address: "70 Example Beauchamp, Princeton, TX 75407",
        phone: "(469) 555-0414",
        hours: hrs("6:30 a.m. – 5:30 p.m.", "7:00 a.m. – 12:00 p.m."),
        amenities: ["Builder punch lists", "Wind-load hardware", "Two- and three-car", "Inspection callbacks"],
        photoStyle: "contemporary",
        photoTint: "#3e4a3c",
        lat: 33.18,
        lng: -96.52,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "pr-4",
        name: "Longneck Overhead",
        slug: "longneck-overhead",
        blurb: "Mock listing used to show a small-town-core replacement card next to the new-construction majority.",
        address: "15 Sample Second St, Princeton, TX 75407",
        phone: "(972) 555-0419",
        hours: hrs("8:00 a.m. – 4:30 p.m.", "Closed"),
        amenities: ["Existing-opening replacement", "Written measure", "Insulation upgrades", "Local core jobs"],
        photoStyle: "wood",
        photoTint: "#6e4a2c",
        lat: 33.181,
        lng: -96.499,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.1801,
    lng: -96.4989,
    mapLabel: "Princeton, TX",
    related: ["mckinney", "anna", "melissa", "celina"],
  },
  {
    slug: "frisco",
    name: "Frisco",
    shortName: "Frisco",
    county: "Collin County (city also reaches Denton County)",
    path: "/tx/frisco/garage-door-install/",
    h1: "Garage door installation in Frisco",
    title: "Garage Door Installation Frisco TX | New Garage Door Frisco",
    description:
      "Garage door installation in Frisco, Texas. 236,955 residents, 1,090 one-unit permits in 2025. Multifamily spiked total units to 5,652 — this page stays on one-unit install.",
    kicker: "Still a top 1-unit suburb — ignore the multifamily spike",
    intro: [
      "Frisco is easy to misread: 236,955 people, 1,090 one-unit permits, and 5,652 total units in 2025. The total-units spike is multifamily. This page stays on leftover single-family lots and replacement in the existing SF stock, not podium parking.",
    ],
    stats: [
      { label: "Population", value: "236,955", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+18.2%", note: "2024→2025 growth was only +0.8%" },
      { label: "2025 1-unit permits", value: "1,090", note: "The install proxy; total units 5,652 are mostly multifamily" },
    ],
    sections: [
      {
        id: "do-not-follow-total-units",
        title: "Do not follow total units into the garage",
        paragraphs: [
          "1,090 one-unit is still a serious install market, plus replacement only a large 1990s–2010s suburb can have. Population growth flattened (+0.8% from 2024 to 2025). Some houses people call Frisco are permitted in Denton County; 1,090 is a lower bound for the named city office.",
          "Frisco's 2020 base was 200,531; the city added 36,424 people (+18.2%) before growth flattened to +0.8% from 2024 to 2025. One-unit permits eased to 1,090 from 1,285, even as total authorized units jumped from 1,333 to 5,652 — the South's largest 2025 increase in total units (+4,319). That spike is multifamily (5+), a weaker garage-door install proxy than one-unit. Frisco sits on the Collin spine and also reaches Denton County; 1,090 is a lower bound for the named city office. City-level housing-unit stock is unknown. Install here means leftover single-family lots and planned replacement in existing openings. Repair — springs, cables, openers on an existing door — is out of scope.",
        ],
      },
    ],
    neighborhoods: [
      { name: "Remaining SF lots / northern fringe", note: "True new-construction doors; 1,090-permit world." },
      { name: "Established west and central SF", note: "Replacement in existing openings; stock size unknown at city level." },
      { name: "Mixed-use / multifamily cores", note: "Not the garage-door install product. Out of scope." },
      { name: "Denton County side of the city", note: "May be permitted outside the Frisco place office." },
    ],
    toc: [
      { id: "intro", label: "Frisco snapshot" },
      { id: "listings", label: "Installers" },
      { id: "do-not-follow-total-units", label: "Ignore multifamily" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "fr-1",
        name: "Cottonwood Creek Doorworks",
        slug: "cottonwood-creek-doorworks",
        blurb: "Mock Frisco shop for replacement and leftover-lot installs in existing single-family sections.",
        address: "5800 Sample Cottonwood, Frisco, TX 75034",
        phone: "(972) 555-0502",
        hours: hrs("7:30 a.m. – 5:30 p.m.", "8:00 a.m. – 1:00 p.m."),
        amenities: ["Existing-opening replacement", "HOA submittals", "Carriage overlays", "Insulation upgrades"],
        photoStyle: "carriage",
        photoTint: "#553820",
        lat: 33.149,
        lng: -96.86,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fr-2",
        name: "Panther Creek Overhead",
        slug: "panther-creek-overhead",
        blurb: "Sample contemporary-door listing for newer Frisco elevations, not apartments.",
        address: "3200 Fiction Panther Creek, Frisco, TX 75033",
        phone: "(214) 555-0508",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "9:00 a.m. – 12:00 p.m."),
        amenities: ["Full-view / contemporary", "Paint-match to stone", "Quiet belt drive", "Smart opener setup"],
        photoStyle: "glass",
        photoTint: "#3a454c",
        lat: 33.175,
        lng: -96.82,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fr-3",
        name: "Hall Park Panel & Track",
        slug: "hall-park-panel-track",
        blurb: "Invented east-Frisco crew for remaining one-unit lots and first replacements.",
        address: "900 Example Hall Park Dr, Frisco, TX 75034",
        phone: "(469) 555-0513",
        hours: hrs("7:00 a.m. – 6:00 p.m.", "7:00 a.m. – 2:00 p.m."),
        amenities: ["New one-unit installs", "Three-car layouts", "Builder punch lists", "Wind-load hardware"],
        photoStyle: "flush",
        photoTint: "#5a5044",
        lat: 33.132,
        lng: -96.79,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "fr-4",
        name: "Starwood Carriage Co.",
        slug: "starwood-carriage-co",
        blurb: "Mock replacement-leaning card for older Frisco single-family streets.",
        address: "44 Sample Starwood Lane, Frisco, TX 75034",
        phone: "(972) 555-0517",
        hours: hrs("8:00 a.m. – 4:30 p.m.", "Closed"),
        amenities: ["Same-size replacement", "Color-match to faded brick", "Opener included", "Written measure"],
        photoStyle: "wood",
        photoTint: "#6a4024",
        lat: 33.16,
        lng: -96.84,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.1507,
    lng: -96.8236,
    mapLabel: "Frisco, TX",
    related: ["celina", "mckinney", "denton", "fort-worth"],
  },
  {
    slug: "denton",
    name: "Denton",
    shortName: "Denton",
    county: "Denton County",
    path: "/tx/denton/garage-door-install/",
    h1: "Garage door installation in Denton",
    title: "Garage Door Installation Denton TX | New Garage Door Denton",
    description:
      "Garage door installation in Denton, Texas. Population 169,431 (+21.1% since 2020). 898 one-unit permits in 2025, up from 856 in 2024 — the rare suburb still rising.",
    kicker: "County seat where 1-unit was still rising in 2025",
    intro: [
      "Denton is the northern county seat: 169,431 people (+21.1%) and 898 one-unit permits in 2025, up from 856. Celina, McKinney, Princeton, Anna, and Melissa all cooled; Denton’s city office did not. New doors sit south and west plus the I-35 / Loop 288 fringe; the square is replacement.",
    ],
    stats: [
      { label: "Population", value: "169,431", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+21.1%", note: "+29,533 people" },
      { label: "2025 1-unit permits", value: "898", note: "Rising vs 856 in 2024" },
    ],
    sections: [
      {
        id: "rising-when-peers-cooled",
        title: "Rising when peers cooled",
        paragraphs: [
          "County one-unit (6,357) is the broader map; city one-unit (898) is this URL. Students and the two universities explain population better than garage doors. Homeowners in the south and west belts are the product.",
          "Denton's 2020 base was 139,898; the city added 29,533 people (+21.1%), and total authorized units climbed to 3,438 in 2025 from 1,976. Denton County permitted 6,357 one-unit homes in 2025, behind only Collin (11,136) and Tarrant (8,658); the city's 898 one-unit print — up from 856 — sits inside that county count and is the rare 2025 suburb office that still rose. Denton is the northern county seat on the growth spine, west of Collin's newer suburbs. Install on this page is a door on new one-unit construction south and west of downtown, or a planned replacement in an older opening. Broken springs and openers on an existing door are out of scope.",
        ],
      },
    ],
    neighborhoods: [
      { name: "South and west belts", note: "Primary new one-unit; production steel doors." },
      { name: "I-35 / Loop 288 fringe", note: "Still-adding sections; builder calendars." },
      { name: "Near the square", note: "Replacement in older openings; not the 898-permit story." },
      { name: "Unincorporated Denton County (not this city office)", note: "Mentioned so searchers do not force a city pin." },
    ],
    toc: [
      { id: "intro", label: "Denton snapshot" },
      { id: "listings", label: "Installers" },
      { id: "rising-when-peers-cooled", label: "Still rising" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "de-1",
        name: "Square District Door Co.",
        slug: "square-district-door-co",
        blurb: "Mock near-square replacement shop — install, not emergency repair.",
        address: "220 Sample Locust St, Denton, TX 76201",
        phone: "(940) 555-0601",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "9:00 a.m. – 1:00 p.m."),
        amenities: ["Existing-opening replacement", "Wood-look steel", "Written measure", "Color-match"],
        photoStyle: "wood",
        photoTint: "#5a3a22",
        lat: 33.215,
        lng: -97.133,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "de-2",
        name: "Hickory Creek Overhead",
        slug: "hickory-creek-overhead",
        blurb: "Sample south-Denton installer for new one-unit and first replacements.",
        address: "4800 Fiction Teasley, Denton, TX 76210",
        phone: "(940) 555-0607",
        hours: hrs("7:00 a.m. – 6:00 p.m.", "8:00 a.m. – 2:00 p.m."),
        amenities: ["New-construction installs", "Insulated flush", "Two-car doubles", "Opener packages"],
        photoStyle: "flush",
        photoTint: "#61564a",
        lat: 33.17,
        lng: -97.14,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "de-3",
        name: "Rayzor Ranch Doors",
        slug: "rayzor-ranch-doors",
        blurb: "Invented west-side crew name for still-adding Denton sections.",
        address: "1100 Example University Dr W, Denton, TX 76207",
        phone: "(940) 555-0612",
        hours: hrs("7:30 a.m. – 5:30 p.m.", "8:00 a.m. – 12:00 p.m."),
        amenities: ["Builder punch lists", "Carriage upgrades", "HOA packets", "Wi-Fi opener setup"],
        photoStyle: "carriage",
        photoTint: "#4c3324",
        lat: 33.232,
        lng: -97.17,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "de-4",
        name: "Southridge Install Works",
        slug: "southridge-install-works",
        blurb: "Mock listing for Loop 288–south new houses, including three-car layouts.",
        address: "60 Sample Colorado Blvd, Denton, TX 76205",
        phone: "(940) 555-0618",
        hours: hrs("6:30 a.m. – 5:00 p.m.", "7:00 a.m. – 1:00 p.m."),
        amenities: ["Three-car openings", "Wind-load tracks", "Inspection callbacks", "Saturday builder slots"],
        photoStyle: "contemporary",
        photoTint: "#3f4c48",
        lat: 33.19,
        lng: -97.12,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.2148,
    lng: -97.1331,
    mapLabel: "Denton, TX",
    related: ["frisco", "celina", "fort-worth", "mckinney"],
  },
  {
    slug: "anna",
    name: "Anna",
    shortName: "Anna",
    county: "Collin County",
    path: "/tx/anna/garage-door-install/",
    h1: "Garage door installation in Anna",
    title: "Garage Door Installation Anna TX | New Garage Door Anna",
    description:
      "Garage door installation in Anna, Texas. Population 35,245 (+105.7% since 2020) with 864 one-unit permits in 2025. US-75 north Collin install directory.",
    kicker: "US-75 north Collin — still high 1-unit",
    intro: [
      "Anna is the US-75 north Collin name that more than doubled this decade: 35,245 people (+105.7%) and 864 one-unit permits in 2025. Pair it with Melissa immediately south and Princeton to the southeast. This is new-construction first, even after cooling from 1,173 in 2024.",
    ],
    stats: [
      { label: "Population", value: "35,245", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+105.7%", note: "+18,108 people; 2024→2025 +10.2%" },
      { label: "2025 1-unit permits", value: "864", note: "BPS; 2024: 1,173" },
    ],
    sections: [
      {
        id: "us75-cluster",
        title: "The US-75 cluster",
        paragraphs: [
          "People in a new section will search the city on the welcome packet, which may not match the permit office. 864 one-unit is just under Denton and well above Melissa. Master-plan product: insulated steel, two-car common, carriage as an upgrade.",
          "Anna's 2020 base was 17,137; the city added 18,108 people (+105.7%), with growth still running at +10.2% from 2024 to 2025 even as one-unit permits cooled to 864 from 1,173. A superseded Vintage 2024 press release ranked Anna #5 among the fastest-growing U.S. places of 20k+ for 2023–24. Anna is a named northern Collin city on the US-75 spine, paired with Melissa immediately south and Princeton to the southeast — not a mill page for an unnamed subdivision. Collin County permitted 11,136 one-unit homes in 2025. Install here means a new door on a new one-unit house, or a planned replacement. Repair — springs, cables, openers on an existing door — is out of scope.",
        ],
      },
    ],
    neighborhoods: [
      { name: "US-75 / master-plan north", note: "New two- and three-car openings; builder calendars." },
      { name: "Toward Melissa", note: "Search overlap; use both city pages." },
      { name: "Older town core", note: "Small replacement set." },
      { name: "East toward Princeton", note: "Same Collin wave; different named city." },
    ],
    toc: [
      { id: "intro", label: "Anna snapshot" },
      { id: "listings", label: "Installers" },
      { id: "us75-cluster", label: "US-75 cluster" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "an-1",
        name: "US-75 North Door Co.",
        slug: "us-75-north-door-co",
        blurb: "Mock Anna installer for production new-construction on the highway spine.",
        address: "900 Sample State Highway 5, Anna, TX 75409",
        phone: "(972) 555-0702",
        hours: hrs("7:00 a.m. – 6:00 p.m.", "8:00 a.m. – 2:00 p.m."),
        amenities: ["New-construction installs", "Same-street multi-house days", "Insulated steel", "Opener packages"],
        photoStyle: "flush",
        photoTint: "#5c5246",
        lat: 33.36,
        lng: -96.55,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "an-2",
        name: "Slayter Creek Overhead",
        slug: "slayter-creek-overhead",
        blurb: "Sample carriage-style shop for HOA elevations in Anna master plans.",
        address: "300 Fiction Slayter Creek, Anna, TX 75409",
        phone: "(214) 555-0708",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "9:00 a.m. – 1:00 p.m."),
        amenities: ["Carriage overlays", "HOA JPEGs", "Color-match", "Quiet belt drive"],
        photoStyle: "carriage",
        photoTint: "#4a3326",
        lat: 33.345,
        lng: -96.56,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "an-3",
        name: "Collin Farms Carriage",
        slug: "collin-farms-carriage",
        blurb: "Invented name for farmland-to-subdivision installs on Anna’s edge.",
        address: "55 Example White Ave, Anna, TX 75409",
        phone: "(469) 555-0714",
        hours: hrs("6:30 a.m. – 5:30 p.m.", "7:00 a.m. – 12:00 p.m."),
        amenities: ["New-slab scheduling", "Wind-load hardware", "Two- and three-car", "Builder punch lists"],
        photoStyle: "wood",
        photoTint: "#6d4a2e",
        lat: 33.3496,
        lng: -96.53,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "an-4",
        name: "Anna Crossing Install",
        slug: "anna-crossing-install",
        blurb: "Mock listing used to show three-car and inspection-callback amenities.",
        address: "1200 Sample Ferguson Pkwy, Anna, TX 75409",
        phone: "(972) 555-0719",
        hours: hrs("7:30 a.m. – 5:00 p.m.", "Closed"),
        amenities: ["Three-car openings", "Inspection-day callbacks", "Wi-Fi opener setup", "Written measure"],
        photoStyle: "contemporary",
        photoTint: "#3d4945",
        lat: 33.34,
        lng: -96.5486,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.3496,
    lng: -96.5486,
    mapLabel: "Anna, TX",
    related: ["melissa", "princeton", "mckinney", "celina"],
  },
  {
    slug: "melissa",
    name: "Melissa",
    shortName: "Melissa",
    county: "Collin County",
    path: "/tx/melissa/garage-door-install/",
    h1: "Garage door installation in Melissa",
    title: "Garage Door Installation Melissa TX | New Garage Door Melissa",
    description:
      "Garage door installation in Melissa, Texas. Population 29,969 (+115.6% since 2020) with 553 one-unit permits in 2025. North Collin install directory paired with Anna and McKinney.",
    kicker: "Permits cooled; growth and install demand did not vanish",
    intro: [
      "Melissa is the smallest of the eight by population and 2025 one-unit count, and it is still an install page: 29,969 people (+115.6%) and 553 one-unit permits. Permits cooled hard from 1,263 in 2024; growth did not vanish (+14.5% last year). This sits on the US-75 / SH-121 seam between McKinney and Anna.",
    ],
    stats: [
      { label: "Population", value: "29,969", note: "1 Jul 2025 · Vintage 2025 PEP" },
      { label: "Since 2020", value: "+115.6%", note: "+16,069 people; 2024→2025 +14.5%" },
      { label: "2025 1-unit permits", value: "553", note: "Cooled vs 1,263 in 2024; still first-wave" },
    ],
    sections: [
      {
        id: "cooled-not-done",
        title: "Cooled, not done",
        paragraphs: [
          "Dropping Melissa would leave a hole between McKinney and Anna. Last year’s 1,263 new houses are now occupied streets whose owners will search this city name for a replacement. That is still install.",
          "Melissa's 2020 base was 13,900; the city added 16,069 people (+115.6%). A superseded Vintage 2024 press release ranked it #11 among the fastest-growing U.S. places of 20k+ for 2023–24. One-unit permits cooled to 553 in 2025 from 1,263 in 2024; that is still first-wave install volume on the US-75 / Collin north cluster with McKinney, Anna, and Princeton. Install on this page is a new door on a 2025 one-unit house, or a planned replacement on the 2024 cohort now occupying those streets. A broken spring, cable, or opener is repair, which this directory does not cover.",
        ],
      },
    ],
    neighborhoods: [
      { name: "SH-121 / US-75 seam", note: "Primary new product; overlap with Anna and McKinney search." },
      { name: "Creekside / ridge master plans", note: "Carriage upgrades and HOA packets." },
      { name: "2010s interior streets", note: "First replacement wave on existing openings." },
      { name: "Town core", note: "Small; not the permit story." },
    ],
    toc: [
      { id: "intro", label: "Melissa snapshot" },
      { id: "listings", label: "Installers" },
      { id: "cooled-not-done", label: "Cooled, not done" },
      { id: "neighborhoods", label: "Areas" },
      { id: "more-cities", label: "Other DFW cities" },
      { id: "map", label: "Area map" }
    ],
    listings: [
      {
        id: "me-1",
        name: "Stiff Creek Doorworks",
        slug: "stiff-creek-doorworks",
        blurb: "Mock Melissa shop for new-construction steel on still-releasing streets.",
        address: "700 Sample Melissa Rd, Melissa, TX 75454",
        phone: "(972) 555-0802",
        hours: hrs("7:00 a.m. – 5:30 p.m.", "8:00 a.m. – 1:00 p.m."),
        amenities: ["New-construction installs", "Insulated steel", "Two-car doubles", "Opener packages"],
        photoStyle: "flush",
        photoTint: "#5b5146",
        lat: 33.286,
        lng: -96.572,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "me-2",
        name: "Melissa Ridge Overhead",
        slug: "melissa-ridge-overhead",
        blurb: "Sample carriage-style listing for HOA elevations in newer Melissa sections.",
        address: "210 Fiction Ridge St, Melissa, TX 75454",
        phone: "(214) 555-0808",
        hours: hrs("8:00 a.m. – 5:00 p.m.", "9:00 a.m. – 12:00 p.m."),
        amenities: ["Carriage overlays", "HOA JPEGs", "Color-match", "Quiet belt drive"],
        photoStyle: "carriage",
        photoTint: "#4d3426",
        lat: 33.295,
        lng: -96.58,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "me-3",
        name: "Liberty Circle Carriage",
        slug: "liberty-circle-carriage",
        blurb: "Invented name pairing Melissa with nearby US-75 lots people still search as Melissa.",
        address: "40 Example SH-121, Melissa, TX 75454",
        phone: "(469) 555-0813",
        hours: hrs("6:30 a.m. – 6:00 p.m.", "7:00 a.m. – 2:00 p.m."),
        amenities: ["Builder punch lists", "Three-car layouts", "Wind-load hardware", "Same-street multi-house days"],
        photoStyle: "wood",
        photoTint: "#704c30",
        lat: 33.278,
        lng: -96.56,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
      {
        id: "me-4",
        name: "Meadow Ridge New Doors",
        slug: "meadow-ridge-new-doors",
        blurb: "Mock replacement-and-new hybrid for 2010s Melissa streets plus leftover lots.",
        address: "18 Sample Fannin Rd, Melissa, TX 75454",
        phone: "(972) 555-0818",
        hours: hrs("8:00 a.m. – 4:30 p.m.", "Closed"),
        amenities: ["Same-size replacement", "Insulation upgrades", "Written measure", "Homeowner scheduling"],
        photoStyle: "contemporary",
        photoTint: "#414a46",
        lat: 33.2859,
        lng: -96.585,
        serviceNotes: SAMPLE_DISCLAIMER,
      },
    ],
    lat: 33.2859,
    lng: -96.5725,
    mapLabel: "Melissa, TX",
    related: ["anna", "mckinney", "princeton", "celina"],
  },
] as CityPage[];

export const CITY_BY_SLUG: Record<string, CityPage> = Object.fromEntries(
  CITIES.filter((city): city is CityPage => Boolean(city && city.slug)).map(
    (city) => [city.slug, city] as [string, CityPage],
  ),
);

export function cityBySlug(slug: string): CityPage | undefined {
  return CITY_BY_SLUG[slug];
}

export const CITY_PATHS = CITIES.filter((c): c is CityPage => Boolean(c && c.path)).map((c) => c.path);

export const ALL_PATHS = [HUB.path, ...CITY_PATHS];

export const LISTINGS = HUB.listings;

export const HOME_PATH = "/";
